parameters:
    default_cdn_strategy: "id"
    APP_URL: "%env(string:default:default_whitespace:APP_URL)%"

shopware:
    filesystem:
        private:
            type: "local"
            config:
                root: "%kernel.project_dir%/files"
        public:
            type: "local"
            config:
                root: "%kernel.project_dir%/public"
        temp:
            type: "local"
            config:
                root: "%kernel.project_dir%/var"
        theme:
        asset:
        sitemap:
        allowed_extensions: ["jpg", "jpeg", "png", "webp", "gif", "svg", "bmp", "tiff", "tif", "eps", "webm", "mkv", "flv", "ogv", "ogg", "mov", "mp4", "avi", "wmv", "pdf", "aac", "mp3", "wav", "flac", "oga", "wma", "txt", "doc", "ico"]

    cdn:
        url: ''
        strategy: "%env(string:default:default_cdn_strategy:SHOPWARE_CDN_STRATEGY_DEFAULT)%"

    api:
        max_limit: 500
        api_browser:
            auth_required: true
        store:
            context_lifetime: 'P1D' # 1 day interval, see also https://www.php.net/manual/en/dateinterval.construct.php#refsect1-dateinterval.construct-parameters
    admin_worker:
        enable_admin_worker: true
        # This has to be lower than PHP's max_execution_time (default: 30s)
        poll_interval: 20
        transports: ["default"]

    auto_update:
        enabled: true

    store:
        frw: false

    sitemap:
        batchsize: 100
        custom_urls:
        excluded_urls:

    deployment:
        blue_green: '%env(bool:default:defaults_bool_true:BLUE_GREEN_DEPLOYMENT)%'

    media:
        enable_url_upload_feature: true
        enable_url_validation: true

    feature:
        flags:
            - name: FEATURE_NEXT_7453
              major: true
              description: "use custom name prefix for nested routes"
              # issue: NEXT-12256
            - name: FEATURE_NEXT_8172
              major: true
              description: "prevent plugins to extend the first level menu entries"
              # issue: NEXT-12267 # TODO: changelog
            - name: FEATURE_NEXT_12009
              major: true
              description: "remove countries from sales channel object inside context"
              # issue: NEXT-13750
            - name: FEATURE_NEXT_10549
              major: false
              description: "save cart or products on wishlist"
            - name: FEATURE_NEXT_10078
              major: false
              description: "cms product page layouts"
            - name: FEATURE_NEXT_12092
              default: false
              major: true
              description: "correct spelling of a config key"
              # issue: NEXT-13751
            - name: FEATURE_NEXT_11253
              default: false
              major: true
              description: "reduce request payload of cms listing"
              # issue: NEXT-13752
            - name: FEATURE_NEXT_10550
              default: false
              major: false
              description: "add rich-text editor with variables"
            - name: FEATURE_NEXT_12016
              default: false
              major: false
              description: "improve promotions UX"
            - name: FEATURE_NEXT_11917
              major: false
              description: "dynamic plugin acl privileges"
            - name: FEATURE_NEXT_10553
              default: false
              major: false
              description: "From prices for variant products"
            - name: FEATURE_NEXT_12108
              default: false
              major: true
              description: "show property group in rule builder and dpg"
              # issue: NEXT-13753
            - name: FEATURE_NEXT_10552
              default: false
              major: true
              description: "custom search index and ranking"
              # issue: NEXT-13539
            - name: FEATURE_NEXT_12553
              default: false
              major: true
              description: "Improve template hierarchy resolving"
              # issue: NEXT-13754 # TODO: changelog
            - name: FEATURE_NEXT_12608
              default: false
              major: true
              description: "App System Store"
            # issue: NEXT-13469
            - name: FEATURE_NEXT_12032
              default: false
              major: true
              description: "Add landing pages"
              # issue: NEXT-13755
            - name: FEATURE_NEXT_12246
              default: false
              major: true
              description: "Exchange standard mailer SwiftMailer to Symfony/Mailer"
              # issue: NEXT-13756
            - name: FEATURE_NEXT_12942
              default: false
              major: true
              description: "Add maximum width for logo"
              # issue: NEXT-13757
            - name: FEATURE_NEXT_12957
              default: false
              major: true
              description: "Separate plugin download and update action"
              # issue: NEXT-13758
            - name: FEATURE_NEXT_9831
              default: false
              major: false
              description: "Filters & Search for Admin Grids"
            - name: FEATURE_NEXT_12429
              default: false
              major: true
              description: "Improve product UX"
              # issue: NEXT-13759
            - name: FEATURE_NEXT_12349
              default: false
              major: true
              description: "Group migrations into major versions"
              # issue: NEXT-13749
            - name: FEATURE_NEXT_12158
              default: false
              major: false
              description: "Refactoring of Elasticsearch"
            - name: FEATURE_NEXT_13273
              default: false
              major: true
              description: "Make CMS entities versionable"
            - name: FEATURE_NEXT_13504
              default: false
              major: true
              description: "Improve category UX"
              # issue: NEXT-13760

    logger:
        file_rotation_count: 14
